import styles from '../styles/Home.module.css'
import Link from 'next/link';
import PageTemplate from '../components/template'

export default function SetupInstructions() {
  return (
  <PageTemplate>
        <h1 className={styles.setupTitle}>
          Setting up your Ledger
        </h1>

        <p className={styles.steps}>
          <div className="inline-block font-bold">Step 1:</div> Initialize your Ledger device and download the Bitcoin app
        </p>
      
        <p className={styles.steps}>
          <div className="inline-block font-bold">Step 2:</div> In the Bitcoin app, add an account then click on the "Show all address types" toggle
        </p>
      
        <p className={styles.steps}>
          <div className="inline-block font-bold">Step 3:</div> Select "Legacy" address and add the account.  This is the address that will connect to Counterparty-HW.
        </p>
      
        <div className="mb-4"><p className={styles.steps}>
          Counterparty-HW connects only to the first Legacy address generated by the Ledger device.  The BIP 32 derivation path is 44'/0'/0'/0/0.
        </p></div>

        <div className={styles.grid}>
            <Link href="/">
              <a href="#" className={styles.card}>
                <p>&larr; Back to home</p>
              </a>
            </Link>
        </div>
    </PageTemplate>
  )
}
